server.ssl.certificate=classpath:keystore/localhost.pem
server.ssl.certificate-private-key=classpath:keystore/localhost-key.pem

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.missforty-tech.de/realms/missfortyTestRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

spring.security.oauth2.client.registration.whatsapp-client.client-id=whatsapp-backend
spring.security.oauth2.client.registration.whatsapp-client.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.whatsapp-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.whatsapp-client.token-uri=https://keycloak.missforty-tech.de/realms/missfortyTestRealm/protocol/openid-connect/token