spring.profiles.active=dev
server.port=8439
server.servlet.context-path=/mail
spring.security.user.roles=admin

spring.jpa.properties.jakarta.persistence.sharedCache.mode=NONE
spring.jpa.open-in-view=true
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false
mail.smtp.ssl.checkserveridentity=false
#logging.level.web=DEBUG

api.accountBaseurl=https://localhost
api.accountUser=celle2006
api.accountPasswd=Linti21!
api.accountBasePath=user

spring.codec.max-in-memory-size=100MB
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB