spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.missforty-tech.de/realms/missfortyRealm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

spring.security.oauth2.client.registration.whatsapp-client.client-id=whatsapp-backend
spring.security.oauth2.client.registration.whatsapp-client.client-secret=Tdcer1AFrMCEBErwAHlCBHQPJAxjFuSr
spring.security.oauth2.client.registration.whatsapp-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.whatsapp-client.token-uri=https://keycloak.missforty-tech.de/realms/missfortyRealm/protocol/openid-connect/token